config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'post_images#index'
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
  	resources :comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
 	belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
	default_scope -> { order(created_at: :desc) }
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	validates :shop_name, presence: true
  	validates :image, presence: true

	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  def destroy
  	Comment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  	post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
  	post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	def create
	end

	def destroy
	end

private
	def comment_params
    params.require(:comment).permit(:comment)
    end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

# 投稿データの保存
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.order(updated_at: :desc).page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end
# 投稿データのストロングパラメータ
  private
  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@post_images = @user.post_images.page(params[:page]).reverse_order
  	end

  	def edit
    	@user = User.find(params[:id])
  	end

  	def update
    	@user = User.find(params[:id])
    	@user.update(user_params)
    	redirect_to user_path(@user.id)
  	end

private
	
	def user_params
    	params.require(:user).permit(:name, :profile_image)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Like
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{crossorigin: "anonymous", src: "https://kit.fontawesome.com/ffe6531265.js"}
    %link{:href => "https://fonts.googleapis.com/css2?family=Caveat+Brush&family=Playball&family=Secular+One&family=Sniglet:wght@400;800&family=Ultra&display=swap", :rel => "stylesheet"}/
  %body
    = yield

app/views/post_images/_list.html.haml
.main
  .main__image
    .main__image__view-first
      - post_images.each do |post_image|
        = attachment_image_tag post_image, :image, :fill, 650, 500,class: "images",style:"background-position: top center;"
        .main__image__content
          .main__image__content__name
            %b By 
            = post_image.user.name
          .main__image__content__image
            = link_to post_image_path(post_image.id) do
              %i.fa.fa-map-marker
              = post_image.shop_name
          = attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg"
          .main__image__content__comments
            %i.fa.fa-comment
              = link_to "#{post_image.comments.count} コメント", post_image_path(post_image.id)
            %i.fa.fa-heart
              = link_to "#{post_image.favorites.count} いいね", post_image_path(post_image.id)
          .main__image__content__caption
            = post_image.caption
        = paginate post_images

app/views/post_images/index.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"
= render 'post_images/list', post_images: @post_images

app/views/post_images/new.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"
.new
  .new__form
    .new__form__title
      %p.new-title 画像投稿フォーム
      = form_for(@post_image, url: post_images_path) do |f|
        = f.attachment_field :image, class: "post_image"
        %br/
        .form-group.has-icon
        %label.control-label.sr-only ショップ名
        = f.text_field :shop_name, class: "shop_name", placeholder:" タイトル。"
        %span.fa.fa-building.form-control-icon{"aria-hidden" => "true"}
        %br/
        = f.text_area :caption, class: "caption", placeholder:" コメントここに。"
        %hr/
        = f.submit "送信", class: "bottom"

app/views/post_images/show.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"

.post__meta
  .post__meta__top
    = attachment_image_tag @post_image, :image,:fill,500,500, class:"show-images"
  .post__meta__content
    %ul.meta-info-cells.v4.float-wrapper
      %li
        %i.fa.fa-user>
        By
        %a{:href => "#"}
          = @post_image.user.name
        %p 
        %b= @post_image.shop_name
        %p= @post_image.caption
      %li
        %i.fa.fa-calendar
        = @post_image.created_at.strftime('%Y/%m/%d')
    - if @post_image.favorited_by?(current_user)
      %li
        = link_to post_image_favorites_path(@post_image), method: :delete do
          %i.fa.fa-heart{"aria-hidden" => "true", :style => "color: red;"}
          = @post_image.favorites.count
          いいね
    - else
      %li
        = link_to post_image_favorites_path(@post_image), method: :post do
          %i.fa.fa-heart-o{"aria-hidden" => "true"}
          = @post_image.favorites.count
          いいね

      %li
        %i.fa.fa-comment
        %a{:href => "#comments"}= @post_image.comments.count

    #comments.comment-list.bt.style-2
      .float-wrapper
        %h2.comment-count
          = @post_image.comments.count
          件コメント

      %ol
    - @post_image.comments.each do |comment|
      %li.comment
        .comment-body.bb
          .comment-avatar
            .avatar
              = attachment_image_tag comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"

        .comment-text
          .comment-author.clearfix
            %a.link-author{:href => "#"}= comment.user.name
            %span.comment-meta
              %span.comment-date= comment.created_at.strftime('%Y/%m/%d')

          .comment-entry= comment.comment
          - if comment.user == current_user
            %div
              = link_to "削除", post_image_comment_path(comment.post_image, comment), method: :delete, class: "btn btn-danger pull-right"


    = form_for [@post_image, @comment] do |f|
      = f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに"
      = f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right"


      = link_to "削除", post_image_path(@post_image), method: :delete

app/views/template/_header_login.html.haml
.header
 .header__contents
  .header__contents__logo
   =link_to "/" do
    %h1 
     Like
     %i.fas.fa-heart

  .header__contents__logo__nav
   %ul
    %li.header-form
     =link_to "投稿フォーム",new_post_image_path,class:""
    %li.header-mypage
     =link_to "マイページ",user_path(current_user.id)
    %li.header-logout
     =link_to "ログアウト",destroy_user_session_path, method: :delete

app/views/template/_header_unlogin.html.haml
.header
 .header__contents
  .header__contents__logo
   %h1
    Like_
    %i.fas.fa-heart

  .header__contents__logo__nav
   %ul
    %li.header-sign
     =link_to "新規登録", new_user_registration_path,class:""
    %li.header-login
     =link_to "ログイン",user_session_path,class:""

app/views/users/edit.html.haml
.body-wrap
  .form-header
    %h2 プロフィール編集
  .form-body
    = form_for(@user) do |f|
      %label.control-label.sr-only{:for => "inputEmail"} Name
      = f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"


      = attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "img-circle  profile-thumb", fallback: "no_image.jpg"


      = f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form"

      = f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20"

app/views/users/show.html.haml
.main-section
  .header
    -if user_signed_in?
      =render "template/header_login"
    -else
      =render "template/header_unlogin"
.profile-container
  = attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle", fallback: "no_image.jpg"
  %b.profile-name= @user.name

  - if @user.id == current_user.id
    %p= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right"


= render 'post_images/list', post_images: @post_images